run_name: "MRI with 10 components&ensembles, batches=8000/8" # corresponds to exp
test_run: false
batch_size: 8
data_workers: 0
shuffle_dataset: true
num_epoch: 10
lr: 0.0001
step_lr: 500.0
components: 10
ensembles: 10
data_path: "data/*.npy"
train_data_size: 0.75
filter_dim: 32
latent_dim: 64
pos_embed: false
recurrent_model: false
dataset: "2DMRI"
steps: 8000 # will be divided by bacth size
# device: 'cpu'
decoder: false




