run_name: "2DMRI" # corresponds to exp
test_run: false
batch_size: 20
data_workers: 0
shuffle_dataset: true
num_epoch: 10
lr: 0.0001
step_lr: 100.0
components: 9
ensembles: 10
data_path: "data/*.npy"
train_data_size: 0.75
filter_dim: 16 # was 32
latent_dim: 64
pos_embed: false
recurrent_model: false
dataset: "2DMRI"
steps: 100000
decoder: false
channels: 1
model: 'LatentEBM128' # or 'LatentEBM'
ssim_weight: 0.20        # MSE↔SSIM mix
ae_lambda: 1.0         # how strongly AE loss influences the joint loss
run_dir: runs/autoencoder


