run_name: "2DMRI" # corresponds to exp
test_run: false
batch_size: 8
data_workers: 0
shuffle_dataset: true
num_epoch: 10
lr: 0.0001
step_lr: 500.0
components: 4
ensembles: 5
data_path: "data/*.npy"
train_data_size: 0.75
filter_dim: 16 # was 32
latent_dim: 64
pos_embed: false
recurrent_model: false
dataset: "2DMRI"
steps: 100000
decoder: false
channels: 1
model: 'LatentEBM128' # or 'LatentEBM'



