ae_lambda: 1.0         # how strongly AE loss influences the joint loss
batch_size: 16
channels: 1
components: 8
data_path: "data"
data_workers: 0
dataset: "2DMRI"
decoder: false
ensembles: 8
filter_dim: 64 # was 32
latent_dim: 512
lr: 0.00005
model: 'LatentEBM128' # or 'LatentEBM'
num_epoch: 10
pos_embed: false
recurrent_model: false
run_dir: runs/autoencoder
run_name: "2DMRI - with new autoencoder - 100 internal steps - slower linear lr scheduler" # corresponds to exp
shuffle_dataset: true
ssim_weight: 0.20        # MSE↔SSIM mix
step_lr: 100.0
steps: 8000
test_run: false
train_data_size: 0.75
