run_name: "2DMRI - with new autoencoder - 100 internal steps - slower linear lr scheduler" # corresponds to exp
test_run: false
batch_size: 16
data_workers: 0
shuffle_dataset: true
num_epoch: 10
lr: 0.00005
step_lr: 100.0
components: 8
ensembles: 8
data_path: "data"
train_data_size: 0.75
filter_dim: 64 # was 32
latent_dim: 512
pos_embed: false
recurrent_model: false
dataset: "2DMRI"
steps: 8000
decoder: false
channels: 1
model: 'LatentEBM128' # or 'LatentEBM'
ssim_weight: 0.20        # MSE↔SSIM mix
ae_lambda: 1.0         # how strongly AE loss influences the joint loss
run_dir: runs/autoencoder
