run_name: "Clevr_data_on_our_code" # corresponds to exp
test_run: false
batch_size: 2
data_workers: 0
shuffle_dataset: true
num_epoch: 1
lr: 0.001
step_lr: 500.0
components: 4
ensembles: 5
data_path: "data/images_clevr/"
train_data_size: 0.75
filter_dim: 64
latent_dim: 64
pos_embed: false
recurrent_model: false
dataset: "clevr"
steps: 1000
# device: 'cpu'
decoder: false




