run_name: "Clevr_data_on_our_code" # corresponds to exp
test_run: true
batch_size: 12
data_workers: 0
shuffle_dataset: true
num_epoch: 10
lr: 0.001
step_lr: 500.0
components: 4
ensembles: 5
data_path: "data/images_clevr/"
train_data_size: 0.75
filter_dim: 64
latent_dim: 64
pos_embed: false
recurrent_model: false
dataset: "clevr"
steps: 10
# device: 'cpu'
decoder: false




