run_name: "Clevr data on our code"
test_run: false
batch_size: 64
data_workers: 0
shuffle_dataset: true
num_epoch: 2
lr: 0.001
step_lr: 50.0
components: 4
ensembles: 5
data_path: "data/images_clevr/"
train_data_size: 0.75
filter_dim: 256
latent_dim: 256
pos_embed: false
recurrent_model: false
dataset: "clevr"
steps: 640000
decoder: false
channels: 3
model: "LatentEBM"
ssim_weight: 0.20        # MSE↔SSIM mix
ae_lambda: 1.0         # how strongly AE loss influences the joint loss
run_dir: runs/autoencoder