run_name: "clevr data on comet"
test_run: False
batch_size: 4
data_workers: 0
shuffle_dataset: true
num_epoch: 10000 # ORIGINAL: 10000 
lr: 0.001
step_lr: 50.0
components: 4
ensembles: 5
data_path: "data/images_clevr/"
train_data_size: 0.75
filter_dim: 64
latent_dim: 64
pos_embed: false
recurrent_model: false
dataset: "clevr"
steps: 10 # ORIGINAL: 10
decoder: false
channels: 3